apiVersion: v1
kind: Service
metadata:
  name: {{ include "geonsaehelper-ai.fullname" . }}
  labels:
    {{- include "geonsaehelper-ai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ default "http" .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "geonsaehelper-ai.selectorLabels" . | nindent 4 }}
