spring:
  application:
    name: geonsaehelper-ai-server
  ai:
    ollama:
      base-url: http://localhost:11434/
      chat:
        options:
          model: ${app.ai.ollama.model}
      embedding:
        options:
          model: ${app.ai.ollama.embedding-model}
    openai:
      enabled: false

app:
  ai:
    default-provider: OLLAMA
    default-system-prompt: >-
      You are a tutor that helps Geonsae users practice and review content concisely.
    ollama:
      model: gpt-oss:20b
      embedding-model: embeddinggemma:300m
    openai:
      model: gpt-4o-mini
      key: 1234
