### Semantic chunking + embeddings request example
# @timeout 1000000
POST http://akradev.duckdns.org:10000/api/chunks/semantic/embed
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="HUG_POLICY.md"
Content-Type: text/markdown

< 청년전용 보증부월세대출.MD
--WebAppBoundary--
Content-Disposition: form-data; name="chunkSizeHint"

500
--WebAppBoundary
Content-Disposition: form-data; name="maxChunkSize"

1000
--WebAppBoundary
Content-Disposition: form-data; name="mechanicalOverlap"

200
--WebAppBoundary
Content-Disposition: form-data; name="productType"

RENT_YOUTH_MONTHLY
--WebAppBoundary--

### 123
POST akradev.duckdns.org:10000/api/chunks/semantic/search
Content-Type: application/json

{
  "query": {
    "type": "text",
    "text": "신청방법"
  }
}
###
POST http://localhost:6333/collections/geonsaehelper_embeddings/points/scroll
Content-Type: application/json

{
"limit": 10,
"with_payload": true,
"with_vector": false
}

###

